name: Loan_prediction
channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.2.3
  - scikit-learn==1.5.2
  - scipy==1.14.1
